<?php
/**
 * Page-header motion icon. Set $icon to one of work|notes|resume|about|contact
 * and require this file inside the header's .wrap.
 *
 * Same isometric world as the homepage hero, one shared 9s lap, three gesture
 * families: LIFT (work, contact), WRITE (notes, resume), TURN (about). Styles
 * and keyframes live under "page-header icons" in main.css.
 *
 * GENERATED by the session generator morph/icons.py -- edit the geometry
 * there and re-splice, do not hand-edit the coordinates below.
 */
switch ($icon ?? '') {
case 'work': ?>
  <svg class="pgi pgi--work" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(78.14 60.14) scale(1.1206)">
  <polygon class="face" points="0.00,0.00 -13.86,-23.00 -64.09,6.00 -50.23,29.00"/>
  <polygon class="face" points="-19.05,-20.00 -25.11,-30.10 -42.44,-20.10 -36.37,-10.00"/>
  <g class="pgi-rest"><polygon class="face" points="-13.77,5.60 -20.78,-11.50 -46.77,3.50 -39.75,20.60"/></g>
  <g class="pgi-drop"><polygon class="face" points="-10.48,3.25 -19.05,-17.00 -51.96,2.00 -43.39,22.25"/></g>
  <polygon class="face" points="0.00,0.00 13.86,3.00 -36.37,32.00 -50.23,29.00"/>
  </g>
  </svg>
<?php break;

case 'notes': ?>
  <svg class="pgi pgi--notes" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(50.00 46.06) scale(1.3143)">
  <polygon class="face" points="32.91,17.00 0.00,36.00 0.00,38.00 32.91,19.00"/>
  <polygon class="face" points="-32.91,17.00 0.00,36.00 0.00,38.00 -32.91,19.00"/>
  <polygon class="face" points="0.00,-2.00 32.91,17.00 0.00,36.00 -32.91,17.00"/>
  <polygon class="wf soft" points="-2.60,5.50 19.92,18.50 -0.87,30.50 -23.38,17.50"/>
  <polygon class="face" points="0.00,-2.00 32.91,17.00 32.91,-13.00 0.00,-32.00"/>
  <g class="pgi-screen">
  <line class="wf soft write" pathLength="100" style="animation-delay:0.00s" x1="4.33" y1="-25.50" x2="25.98" y2="-13.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.34s" x1="4.33" y1="-20.50" x2="28.58" y2="-6.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.68s" x1="4.33" y1="-15.50" x2="20.78" y2="-6.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:1.02s" x1="4.33" y1="-10.50" x2="25.11" y2="1.50"/>
  </g>
  </g>
  </svg>
<?php break;

case 'resume': ?>
  <svg class="pgi pgi--resume" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(58.26 24.80) scale(1.3620)">
  <polygon class="face" points="27.71,14.00 -12.12,37.00 -12.12,39.00 27.71,16.00"/>
  <polygon class="face" points="-39.84,21.00 -12.12,37.00 -12.12,39.00 -39.84,23.00"/>
  <polygon class="face" points="0.00,-2.00 27.71,14.00 -12.12,37.00 -39.84,21.00"/>
  <line class="wf bold" x1="-1.73" y1="4.00" x2="4.33" y2="7.50"/>
  <line class="wf soft" x1="-6.06" y1="6.50" x2="12.99" y2="17.50"/>
  <g class="pgi-copy">
  <line class="wf soft write" pathLength="100" style="animation-delay:0.00s" x1="-12.99" y1="10.50" x2="-7.79" y2="13.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.00s" x1="-5.20" y1="15.00" x2="6.06" y2="21.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.00s" x1="-8.66" y1="17.00" x2="-0.87" y2="21.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.34s" x1="-20.78" y1="15.00" x2="-15.59" y2="18.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.34s" x1="-12.99" y1="19.50" x2="-1.73" y2="26.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.34s" x1="-16.45" y1="21.50" x2="-8.66" y2="26.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.68s" x1="-28.58" y1="19.50" x2="-23.38" y2="22.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.68s" x1="-20.78" y1="24.00" x2="-9.53" y2="30.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.68s" x1="-24.25" y1="26.00" x2="-16.45" y2="30.50"/>
  </g>
  </g>
  </svg>
<?php break;

case 'about': ?>
  <svg class="pgi pgi--about" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(45.82 47.28) scale(1.2072)">
  <polygon class="face" points="-13.86,32.00 -34.64,6.00 -34.64,8.50 -13.86,34.50"/>
  <polygon class="face" points="20.78,12.00 0.00,-14.00 -34.64,6.00 -13.86,32.00"/>
  <line class="wf soft" x1="7.52" y1="12.82" x2="-4.54" y2="-2.26"/>
  <line class="wf soft" x1="1.45" y1="16.32" x2="-7.27" y2="5.40"/>
  <line class="wf soft" x1="-4.61" y1="19.82" x2="-16.66" y2="4.74"/>
  <line class="wf soft" x1="-10.67" y1="23.32" x2="-19.40" y2="12.40"/>
  <g class="pgi-rpage">
  <polygon class="face" points="-13.86,32.00 6.93,30.00 6.93,32.50 -13.86,34.50"/>
  <polygon class="face" points="41.57,10.00 6.93,30.00 6.93,32.50 41.57,12.50"/>
  <polygon class="face" points="20.78,12.00 41.57,10.00 6.93,30.00 -13.86,32.00"/>
  <line class="wf soft" x1="15.00" y1="17.14" x2="27.05" y2="15.98"/>
  <line class="wf soft" x1="8.94" y1="20.64" x2="17.67" y2="19.80"/>
  <line class="wf soft" x1="2.88" y1="24.14" x2="14.93" y2="22.98"/>
  <line class="wf soft" x1="-3.19" y1="27.64" x2="5.54" y2="26.80"/>
  </g>
  <g class="pgi-turn"><polygon class="face" points="20.78,12.00 41.57,10.00 6.93,30.00 -13.86,32.00"/></g>
  </g>
  </svg>
<?php break;

case 'contact': ?>
  <svg class="pgi pgi--contact" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(45.33 43.10) scale(1.3484)">
  <polygon class="face" points="-22.52,13.00 -22.52,6.00 -22.52,6.00 -22.30,3.34 -21.66,0.53 -20.62,-2.32 -19.22,-5.10 -17.51,-7.70 -15.57,-10.02 -13.45,-11.98 -11.26,-13.50 -9.06,-14.52 -6.95,-15.00 -5.00,-14.92 -3.30,-14.29 -1.90,-13.13 -0.86,-11.48 -0.22,-9.41 0.00,-7.00 0.00,0.00"/>
  <polygon class="face" points="-22.52,6.00 -22.30,3.34 -21.66,0.53 -20.62,-2.32 -19.22,-5.10 -17.51,-7.70 -15.57,-10.02 -13.45,-11.98 -11.26,-13.50 -9.06,-14.52 -6.95,-15.00 -5.00,-14.92 -3.30,-14.29 -1.90,-13.13 -0.86,-11.48 -0.22,-9.41 0.00,-7.00 29.44,10.00 29.23,7.59 28.59,5.52 27.55,3.87 26.15,2.71 24.44,2.08 22.49,2.00 20.38,2.48 18.19,3.50 15.99,5.02 13.88,6.98 11.93,9.30 10.23,11.90 8.83,14.68 7.79,17.53 7.14,20.34 6.93,23.00"/>
  <polygon class="face" points="-22.52,13.00 6.93,30.00 6.93,23.00 -22.52,6.00"/>
  <polygon class="face" points="6.93,30.00 6.93,23.00 6.93,23.00 7.14,20.34 7.79,17.53 8.83,14.68 10.23,11.90 11.93,9.30 13.88,6.98 15.99,5.02 18.19,3.50 20.38,2.48 22.49,2.00 24.44,2.08 26.15,2.71 27.55,3.87 28.59,5.52 29.23,7.59 29.44,10.00 29.44,17.00"/>
  <polygon class="wf soft" points="10.39,26.00 10.39,21.00 10.39,21.00 10.54,19.16 10.99,17.21 11.71,15.24 12.68,13.32 13.86,11.52 15.20,9.91 16.67,8.55 18.19,7.50 19.71,6.80 21.17,6.46 22.52,6.52 23.70,6.95 24.67,7.76 25.39,8.90 25.83,10.33 25.98,12.00 25.98,17.00"/>
  <g class="pgi-flag">
  <polyline class="wf" points="-0.87,23.50 10.48,39.23"/>
  <polygon class="face" points="4.81,31.37 10.48,39.23 13.96,35.50 8.29,27.64"/>
  </g>
  </g>
  </svg>
<?php break;
}
