<?php
/**
 * Page-header motion icon. Set $icon to one of work|notes|resume|about|contact
 * and require this file inside the header's .wrap.
 *
 * Same isometric world as the homepage hero, one shared 9s lap, three gesture
 * families: LIFT (work, contact), WRITE (notes, resume), TURN (about). Styles
 * and keyframes live under "page-header icons" in main.css.
 *
 * GENERATED by the session generator morph/icons.py -- edit the geometry
 * there and re-splice, do not hand-edit the coordinates below.
 */
switch ($icon ?? '') {
case 'work': ?>
  <svg class="pgi pgi--work" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(47.60 38.99) scale(1.2587)">
  <g class="pgi-base">
  <polygon class="face" points="34.64,17.00 0.00,37.00 0.00,40.00 34.64,20.00"/>
  <polygon class="face" points="-34.64,17.00 0.00,37.00 0.00,40.00 -34.64,20.00"/>
  <polygon class="face" points="0.00,-3.00 34.64,17.00 0.00,37.00 -34.64,17.00"/>
  </g>
  <g class="pgi-riseB">
  <polygon class="face" points="25.98,15.80 0.00,30.80 0.00,32.00 25.98,17.00"/>
  <polygon class="face" points="-25.98,15.80 0.00,30.80 0.00,32.00 -25.98,17.00"/>
  <polygon class="face" points="0.00,0.80 25.98,15.80 0.00,30.80 -25.98,15.80"/>
  <line class="wf soft" x1="-2.60" y1="6.30" x2="12.12" y2="14.80"/>
  <line class="wf soft" x1="-7.79" y1="9.30" x2="10.39" y2="19.80"/>
  <line class="wf soft" x1="-12.99" y1="12.30" x2="-1.73" y2="18.80"/>
  </g>
  <g class="pgi-riseA">
  <polygon class="face" points="32.91,13.50 0.00,32.50 0.00,35.00 32.91,16.00"/>
  <polygon class="face" points="-32.91,13.50 0.00,32.50 0.00,35.00 -32.91,16.00"/>
  <polygon class="face" points="0.00,-5.50 32.91,13.50 0.00,32.50 -32.91,13.50"/>
  <polygon class="face" points="38.45,6.70 29.79,11.70 29.79,14.20 38.45,9.20"/>
  <polygon class="face" points="15.24,3.30 29.79,11.70 29.79,14.20 15.24,5.80"/>
  <polygon class="face" points="23.90,-1.70 38.45,6.70 29.79,11.70 15.24,3.30"/>
  </g>
  </g>
  </svg>
<?php break;

case 'notes': ?>
  <svg class="pgi pgi--notes" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(50.00 46.06) scale(1.3143)">
  <polygon class="face" points="32.91,17.00 0.00,36.00 0.00,38.00 32.91,19.00"/>
  <polygon class="face" points="-32.91,17.00 0.00,36.00 0.00,38.00 -32.91,19.00"/>
  <polygon class="face" points="0.00,-2.00 32.91,17.00 0.00,36.00 -32.91,17.00"/>
  <polygon class="wf soft" points="-2.60,5.50 19.92,18.50 -0.87,30.50 -23.38,17.50"/>
  <polygon class="face" points="0.00,-2.00 32.91,17.00 32.91,-13.00 0.00,-32.00"/>
  <g class="pgi-screen">
  <line class="wf soft write" pathLength="100" style="animation-delay:0.00s" x1="4.33" y1="-25.50" x2="25.98" y2="-13.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.34s" x1="4.33" y1="-20.50" x2="28.58" y2="-6.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.68s" x1="4.33" y1="-15.50" x2="20.78" y2="-6.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:1.02s" x1="4.33" y1="-10.50" x2="25.11" y2="1.50"/>
  </g>
  </g>
  </svg>
<?php break;

case 'resume': ?>
  <svg class="pgi pgi--resume" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(58.26 24.80) scale(1.3620)">
  <polygon class="face" points="27.71,14.00 -12.12,37.00 -12.12,39.00 27.71,16.00"/>
  <polygon class="face" points="-39.84,21.00 -12.12,37.00 -12.12,39.00 -39.84,23.00"/>
  <polygon class="face" points="0.00,-2.00 27.71,14.00 -12.12,37.00 -39.84,21.00"/>
  <line class="wf bold" x1="-1.73" y1="4.00" x2="4.33" y2="7.50"/>
  <line class="wf soft" x1="-6.06" y1="6.50" x2="12.99" y2="17.50"/>
  <g class="pgi-copy">
  <line class="wf soft write" pathLength="100" style="animation-delay:0.00s" x1="-12.99" y1="10.50" x2="-7.79" y2="13.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.00s" x1="-5.20" y1="15.00" x2="6.06" y2="21.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.00s" x1="-8.66" y1="17.00" x2="-0.87" y2="21.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.34s" x1="-20.78" y1="15.00" x2="-15.59" y2="18.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.34s" x1="-12.99" y1="19.50" x2="-1.73" y2="26.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.34s" x1="-16.45" y1="21.50" x2="-8.66" y2="26.00"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.68s" x1="-28.58" y1="19.50" x2="-23.38" y2="22.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.68s" x1="-20.78" y1="24.00" x2="-9.53" y2="30.50"/>
  <line class="wf soft write" pathLength="100" style="animation-delay:0.68s" x1="-24.25" y1="26.00" x2="-16.45" y2="30.50"/>
  </g>
  </g>
  </svg>
<?php break;

case 'about': ?>
  <svg class="pgi pgi--about" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(45.82 44.51) scale(1.2072)">
  <polygon class="face" points="-13.86,32.00 -34.64,6.00 -34.64,8.50 -13.86,34.50"/>
  <polygon class="face" points="20.78,12.00 0.00,-14.00 -34.64,6.00 -13.86,32.00"/>
  <line class="wf soft" x1="7.52" y1="12.82" x2="-4.54" y2="-2.26"/>
  <line class="wf soft" x1="1.45" y1="16.32" x2="-7.27" y2="5.40"/>
  <line class="wf soft" x1="-4.61" y1="19.82" x2="-16.66" y2="4.74"/>
  <line class="wf soft" x1="-10.67" y1="23.32" x2="-19.40" y2="12.40"/>
  <g class="pgi-rpage">
  <polygon class="face" points="-13.86,32.00 6.93,30.00 6.93,32.50 -13.86,34.50"/>
  <polygon class="face" points="41.57,10.00 6.93,30.00 6.93,32.50 41.57,12.50"/>
  <polygon class="face" points="20.78,12.00 41.57,10.00 6.93,30.00 -13.86,32.00"/>
  <line class="wf soft" x1="15.00" y1="17.14" x2="27.05" y2="15.98"/>
  <line class="wf soft" x1="8.94" y1="20.64" x2="17.67" y2="19.80"/>
  <line class="wf soft" x1="2.88" y1="24.14" x2="14.93" y2="22.98"/>
  <line class="wf soft" x1="-3.19" y1="27.64" x2="5.54" y2="26.80"/>
  </g>
  <g class="pgi-flip f1"><polygon class="face" points="20.78,12.00 41.57,10.00 6.93,30.00 -13.86,32.00"/></g>
  <g class="pgi-flip f2"><polygon class="face" points="20.78,12.00 35.33,-6.20 0.69,13.80 -13.86,32.00"/></g>
  <g class="pgi-flip f3"><polygon class="face" points="20.78,12.00 24.94,-20.60 -9.70,-0.60 -13.86,32.00"/></g>
  <g class="pgi-flip f4"><polygon class="face" points="20.78,12.00 16.63,-25.40 -18.01,-5.40 -13.86,32.00"/></g>
  <g class="pgi-flip f5"><polygon class="face" points="20.78,12.00 6.24,-23.00 -28.41,-3.00 -13.86,32.00"/></g>
  <g class="pgi-flip f6"><polygon class="face" points="20.78,12.00 0.00,-14.00 -34.64,6.00 -13.86,32.00"/></g>
  </g>
  </svg>
<?php break;

case 'contact': ?>
  <svg class="pgi pgi--contact" viewBox="0 0 100 100" aria-hidden="true">
  <g transform="translate(50.00 40.70) scale(1.3279)">
  <g class="pgi-fold fo3"><polygon class="face" points="0.00,-3.60 34.64,16.40 20.78,-16.00"/></g>
  <polygon class="face" points="34.64,17.00 0.00,37.00 0.00,40.00 34.64,20.00"/>
  <polygon class="face" points="-34.64,17.00 0.00,37.00 0.00,40.00 -34.64,20.00"/>
  <polygon class="face" points="0.00,-3.00 34.64,17.00 0.00,37.00 -34.64,17.00"/>
  <polyline class="wf" points="0.00,-3.00 0.00,17.00 34.64,17.00"/>
  <g class="pgi-riseB">
  <polygon class="face" points="24.25,15.80 0.00,29.80 0.00,31.00 24.25,17.00"/>
  <polygon class="face" points="-24.25,15.80 0.00,29.80 0.00,31.00 -24.25,17.00"/>
  <polygon class="face" points="0.00,1.80 24.25,15.80 0.00,29.80 -24.25,15.80"/>
  <line class="wf soft" x1="-2.60" y1="7.30" x2="12.99" y2="16.30"/>
  <line class="wf soft" x1="-7.79" y1="10.30" x2="10.39" y2="20.80"/>
  <line class="wf soft" x1="-12.99" y1="13.30" x2="-0.87" y2="20.30"/>
  </g>
  <g class="pgi-fold fo1"><polygon class="face" points="0.00,-3.60 34.64,16.40 0.00,16.40"/></g>
  <g class="pgi-fold fo2"><polygon class="face" points="0.00,-3.60 34.64,16.40 6.93,-2.00"/></g>
  </g>
  </svg>
<?php break;
}
